---
engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
    - "**.py"
    - "**.md"
    - "**.sh"
exclude_paths: []
