CREATE TABLE IF NOT EXISTS verificationStatus (
  id INTEGER PRIMARY KEY,
  status VARCHAR(255) NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS HTTPmethods (
  method VARCHAR(10) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS transactions (
  id INTEGER PRIMARY KEY,
  method VARCHAR(10) NOT NULL,
  uri VARCHAR(255) NOT NULL,
  responseStatus INTEGER,
  contentType VARCHAR(255),
  content VARCHAR(255),
  verificationStatusId INTEGER,
  origin VARCHAR(255),
  depth INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS finding (
  id INTEGER PRIMARY KEY NOT NULL,
  responseId INT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS link (
  findingId INTEGER PRIMARY KEY NOT NULL,
  toUri VARCHAR(255) NOT NULL,
  processed BOOLEAN NOT NULL DEFAULT false,
  requestId INT UNSIGNED
);

CREATE TABLE IF NOT EXISTS defectType (
  id INTEGER PRIMARY KEY NOT NULL,
  type VARCHAR(255) NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS defect (
  findingId INTEGER PRIMARY KEY NOT NULL,
  type INT UNSIGNED NOT NULL,
  evidence TEXT NOT NULL,
  severity REAL NOT NULL DEFAULT 0.5
);

CREATE TABLE IF NOT EXISTS cookies (
  findingId INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  value VARCHAR(255) NOT NULL
);
